<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>CensorExtension</AssemblyName>
    <RootNamespace>Censor.MpvNet.Extension</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Censor.Core\Censor.Core.csproj" />
    <Reference Include="libmpvnet">
      <HintPath>..\..\.deps\mpvnet\libmpvnet.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
