<Project>
  <PropertyGroup>
    <Product>CensorPlayer</Product>
    <Version>1.3.1-rc.1</Version>
    <PackageLicenseExpression>GPL-2.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/CBEPX/mpvnet-censor-extension</RepositoryUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
  </PropertyGroup>
</Project>
