# Open the Censor Extension tool window.
Ctrl+Alt+c script-message-to censor censor-open

# Optional direct controls.
Ctrl+Alt+r script-message-to censor censor-reload
Ctrl+Alt+d script-message-to censor censor-disable
